### ISSUE TITLE
데이터 관련 문의드립니다.

### ISSUE THREAD

**Issue by Jeong1889** [SMART-TTS/SMART-Single_Emotional_TTS#2]
안녕하세요. 내년초 공개될 데이터 스펙 관련해서 문의드립니다.

aihub 에서 감정별 데이터셋으로 공개된 음성 데이터셋은 sampling rate가 16k로 공개가 되어 사실상 음성합성 모델 합성용으로 쓰는데는 어려움이 있습니다.

그래서 그런데 이번에 공개될 음성 데이터셋은 sampling rate 22.05kHz 이상으로 녹음이 되었는지 질문드립니다.

감사합니다.

**Comment by Rulunation** [comment]
안녕하세요, 답변을 늦게 드리게 되어 죄송합니다!

올해 공개될 데이터셋은 아직 확정된것은 아니긴 하지만, 22050 이상일 것으로 예상됩니다.
올해 말에 공개가 될 예정이며, 공개 시점에 sampling rate가 변경 될 수도 있다는 점 알려드립니다.

감사합니다.
