### ISSUE TITLE
데이터셋 공개 요청드립니다.

### ISSUE THREAD

**Issue by MonsKim999** [SMART-TTS/SMART-Single_Emotional_TTS#5]
2년이 넘게 공개가 안되다니... 무슨 문제라도 발생했나요?

**Comment by SMART-TTS** [comment]
안녕하세요! 데이터는 7월 초에 AI 허브에 공개되었습니다! 아래 링크 따라가셔서 데이터 사용신청하시면 담당자 검토 후 다운로드 가능하십니다.

https://aihub.or.kr/aihubdata/data/view.do?currMenu=120&topMenu=100&aihubDataSe=extrldata&dataSetSn=637
